FROM mcr.microsoft.com/devcontainers/rust:2-1-trixie

RUN rustup target add x86_64-pc-windows-gnu \
    && rustup component add llvm-tools-preview

# Wine 10.19+ is needed to fix some symlink behaviour.
# <https://gitlab.winehq.org/wine/wine/-/wikis/Debian-Ubuntu>
RUN mkdir -pm755 /etc/apt/keyrings \
    && wget -O - https://dl.winehq.org/wine-builds/winehq.key | gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key - \
    && dpkg --add-architecture i386 \
    && wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/debian/dists/trixie/winehq-trixie.sources

RUN apt-get update && apt-get install -y --no-install-recommends \
    winehq-stable \
    && rm -rf /var/lib/apt/lists/*

USER vscode
WORKDIR /home/vscode

RUN cargo install cargo-vet --version 0.10.2 --locked \
    && rm -rf /usr/local/cargo/registry

RUN curl --proto '=https' --tlsv1.2 -sSfLO https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.8.2/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz \
    && echo "6bd0fba0e70f8399fb4f279e4e00992860edaa9ff7e460cb9b5f924e6018c7eb cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz" | sha256sum -c \
    && tar xzf cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz -C "/usr/local/cargo/bin" \
    && rm cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz

# Run the Windows tests through Wine.
# Set the locale to a UTF-8 locale so that the Unicode filename tests pass.
ENV CARGO_TARGET_X86_64_PC_WINDOWS_GNU_RUNNER=wine \
    LC_ALL=en_US.utf8
